### ISSUE TITLE
extra space 

### ISSUE THREAD

**Issue by MON11** [syntactic/JSGFTools#3]
Probabilistic generator adds a blank space in two contexts: 

1) Blank space appears in place of the optional element when optional element is skipped. The result is two consecutive blank spaces in the expanded grammar. Removing spaces between characters in grammar has no effect. 

<img width="653" alt="screen shot 2018-01-26 at 8 26 27 am" src="https://user-images.githubusercontent.com/35844974/35449725-b04d670a-0272-11e8-9001-602afbbfb38b.png">

<img width="598" alt="screen shot 2018-01-26 at 8 25 34 am" src="https://user-images.githubusercontent.com/35844974/35449745-b938c7c4-0272-11e8-8b8f-7c23437c65f2.png">

2) There is also an extra space before the "?".

**Comment by syntactic** [comment]
Thanks for reporting this - I've gone ahead and fixed it in commit c7ae58a.
